service: arithfi-periphery
provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1

plugins:
  - serverless-dotenv-plugin

useDotenv: true

package:
  patterns:
    - "!./**"
    - "./bin/**"
functions:
  time:
    handler: bin/api/time
    memorySize: 256
    events:
      - http:
          path: /time
          method: get
  klines:
    handler: bin/api/klines
    memorySize: 256
    events:
      - http:
          path: /klines
          method: get