service: arithfi-periphery
provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1

plugins:
  - serverless-dotenv-plugin

useDotenv: true

package:
  patterns:
    - "!./**"
    - "./bin/**"
functions:
  streams:
    handler: bin/api/hello
    events:
      - http:
          path: /hello
          method: post