service: arithfi-periphery
provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1

plugins:
  - serverless-dotenv-plugin

useDotenv: true

package:
  patterns:
    - "!./**"
    - "./bin/**"
functions:
  account_assets:
    handler: bin/api/account/assets
    events:
      - http:
          path: /api/account/assets
          method: get
  hello:
    handler: bin/api/hello
    events:
      - http:
          path: /api/hello
          method: get