service: arithfi-periphery
provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1

plugins:
  - serverless-dotenv-plugin

useDotenv: true

package:
  patterns:
    - "!./**"
    - "./bin/**"
functions:
  ping:
    handler: bin/api/ping
    events:
      - http:
          path: /ping
          method: get
  time:
    handler: bin/api/time
    events:
      - http:
          path: /time
          method: get
  klines:
    handler: bin/api/klines
    events:
      - http:
          path: /klines
          method: get